### PR TITLE
Add label key for pool location constraint

### PR DESCRIPTION
**Pull request by harsh-px**
Signed-off-by: Harsh Desai <harsh@portworx.com>

**What this PR does / why we need it**:

Will be using this to enumerate volumes based on pool uuids.

**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sangleganesh** [comment]
why not use existing LocationContraint ?

**Comment by harsh-px** [comment]
> why not use existing LocationContraint ?

Since that is already being processed for node IDs.  I can overload LocationContraint to contain both node IDs or pool UIDs and compare the string specified in LocationContraint with both node IDs and the volumes pool IDs. But with that, the parsing code won't look clean. Opted for a more specific check.

Let me know if you have a strong preference.

**Comment by sangleganesh** [comment]
we can continue to LocationConstraint, since it does not specify node id only.

**Comment by harsh-px** [comment]
Using existing LocationConstraint instead of adding a new key

**Pull request closed without merging**
