### PR TITLE
Builds osd binary in docker container and copy osd image to host.

### PR DESCRIPTION
**Pull request by kunalkushwaha**
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>

### CODE REVIEW

**Comment by peter-edge** [comment]
This won't work for OS X, for example, if there was ever a desire for a platform-agnostic client (you'd have to do a cross-compile build). With the new docker images, I'm not sure if this is relevant anymore, shoot.

**Comment by jvinod** [comment]
@peter-edge what's the recommended way to get a binary on your box with the build done in docker

**Comment by peter-edge** [comment]
docker cp, I am on my phone right now but I'll link you an example in a bit.

**Comment by jvinod** [comment]
cool...how;s that different from just -v 'ing?

**Comment by peter-edge** [comment]
Remote machines - if you are running from Mac, connecting to a machine
that's not a local vm, host volumes do not apply.

**Comment by jvinod** [comment]
ah

**Comment by kunalkushwaha** [comment]
Hi,

In my dev environment, I use two ways and both works fine.

1. Build osd in docker container and copy to host.
2. Build osd in docker container with folders like /var/lib/plugins,
/var/lib/osd etc mounted in container in privileged mode.
    - Then run the osd using docker exec and another docker exec for volume
creation etc.
    - Benefit of this approach is the whole build and runtime environment
is shared with docker environment, but still independent.

I think second approach can work for OSX also. If docker runs in one
container, folders can be shared with build container of osd.

Regards,
Kunal Kushwaha

------------------------------

**Comment by peter-edge** [comment]
@jvinod what are we doing about this?

**Comment by kunalkushwaha** [comment]
This is no more valid now on current file. Closing this.

**Pull request closed without merging**
