### PR TITLE
Pair clusters

### PR DESCRIPTION
**Pull request by gourao**

### CODE REVIEW

**Comment by gourao** [comment]
CI is fixed

**Comment by lpabon** [comment]
This code is missing a lot of tests

**Comment by venkatpx** [comment]
Luis craking his whip! Go Luis!!

**Comment by lpabon** [comment]
Looks like this work is still in progress.

**Comment by ggriffiths** [comment]
Closing manually as we're closing old PRs before Jan 2020. Feel free to update and re-open if this is still relevant.

**Pull request closed without merging**
