### PR TITLE
Base FUSE volume driver

### PR DESCRIPTION
**Pull request by peter-edge**
This isn't ready for merging yet, I need to find a good example FS to test with.

The concept here is that if someone implements bazil.org/fuse/fs.Filesystem, they can automatically add a volume.VolumeDriver. This would let Pachyderm immediately/generically add PFS as a volume.VolumeDriver, for example.

I basically took the code from the vfs driver, and the common code should be combined I would think. This was more a test for me to get some of the basics.

### CODE REVIEW

**Comment by peter-edge** [comment]
Why this is cool: https://godoc.org/bazil.org/fuse/fs?importers

**Comment by jvinod** [comment]
I see how this can be useful in a variety of ways - even perhaps a remote attach..

**Comment by peter-edge** [comment]
Can we just merge this in for now and I'll work off it?

**Comment by sathieu** [comment]
How can I enable this driver?

**Pull request merged**
