### PR TITLE
Switch to go-dockerclient

### PR DESCRIPTION
**Pull request by peter-edge**
https://github.com/fsouza/go-dockerclient

In my experience, it's the most actively maintained golang docker API client. Kubernetes uses it, among a lot of people. And I also happen to be a maintainer of it :)

### CODE REVIEW

**Comment by jvinod** [comment]
SGTM, we're not tied to the samalba client .. The only potential "breaking" change for our deployment might be that it takes in its config from environment variables::
```
-	docker, err := dockerclient.NewDockerClient(dockerHost, nil)
+	docker, err := docker.NewClientFromEnv()
```
which might affect our deployment.

ping @gourao

**Comment by peter-edge** [comment]
It's the same thing as you have now, if DOCKER_HOST is not set, it defaults
to the default UNIX socket. This constructor also handles DOCKER_TLS_VERIFY
and DOCKER_CERT_PATH.

**Comment by jvinod** [comment]
sure,  we can always set the env. Hypothetically, how do simultaneously talk to two different docker api endpoints?

**Comment by peter-edge** [comment]
Heh. More fun configuration that we can add. You'll have to have a strict
with docker host, TLS verify, CERT path, and then pass it into the
constructor.

**Comment by jvinod** [comment]
:) Are you saying there's already such a constructor ? I  see there's a NewClient(endpoint string) -- that might help?

**Comment by peter-edge** [comment]
Yes :) there's about 20 constructors, half of which I put in the codebase
over time for various reasons :)

**Comment by jvinod** [comment]
Cool :)  Let's  pass in the dockerclient as an explicit argument  instead of env vars?  what do you think ?

**Comment by peter-edge** [comment]
Oh sure, I was just going with what was already there. I'll make that
change now.

**Comment by peter-edge** [comment]
Can we get this in? Want to move on from it :)

**Comment by jvinod** [comment]
oh yes, missed this.

**Pull request merged**
