### PR TITLE
Add GCE storage operations and refactor existing AWS storage operations

### PR DESCRIPTION
**Pull request by harsh-px**
1. Add GCE storage operations
2. Refactor storage operations into a single interface
3. Add go tests for AWS and GCE volume driver (invoked through common storageops_test.go)
4. For AWS driver, refresh EBS volume information in routines that concern with volume metadata

For the AWS storage operations, this is primarily a move of the implementation from the aws driver to pkg/storageops. Changes were made to refactor it as a interface impl.

### CODE REVIEW

**Comment by lpabon** [comment]
There seem to be two changes here. One to AWS and one to GCE. Please split the work to two or more PRs to make it easier to review.

**Comment by harsh-px** [comment]
> There seem to be two changes here. One to AWS and one to GCE. Please split the work to two or more PRs to make it easier to review.

I created a single PR since I added a common `Ops` interface for storage operations and the existing aws implementation had to be moved to this interface. The primary change for this PR is the new GCE implementation.

**Comment by lpabon** [comment]
@harsh-px Yeah, makes sense, but it makes it very hard to review. Please split up to maybe three PRs. The generic part for AWS and GCE, then once that lands, then submit the changes for AWS and GCE PRs. That is just one way.

**Comment by harsh-px** [comment]
@lpabon Sure thing. Closing this one.

**Pull request closed without merging**
