### PR TITLE
[PWX-19922] don't pass shared, sharedv4 flags to pure volume specs

### PR DESCRIPTION
**Pull request by pure-jliao**
**What this PR does / why we need it**: for porx/gs-rel-2.8.0 vendoring

**Which issue(s) this PR fixes** (optional)
Closes # 
PWX-19922 don't pass shared, sharedv4 flags to pure volume specs

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ggriffiths** [comment]
I think you'll need to cherry-pick the pure spec changes first to get this passing

**Comment by pure-jliao** [comment]
> I think you'll need to cherry-pick the pure spec changes first to get this passing

yeah thanks, how about the sdk version in this branch? should it be consistent with master or a separate one? I assume it's a separate version stack.

**Comment by ggriffiths** [comment]
Yeah, separate version - looks like you'll want `v0.101.9`

**Review by ggriffiths — APPROVED** [review]
Looks good - for future cherry-picks, it's okay to merge without approval :)

**Pull request merged**
