### PR TITLE
localfs, a zero-configuration driver 

### PR DESCRIPTION
**Pull request by kunalkushwaha**
Sample code for review and understanding driver code.

Few things is not clear to me.
1. Create()- In create function, the folder structure that is created, doesnt make any sense while mounting.
2. I have not implement, Mount function, since it is not required.
3. After mounting the volume in docker container, the data changes in that mounted folder is reflected in ``/var/lib/docker/volume/<volume-name>``
4. I want to understand, how the create/mount  folder/file is reflected to actual IO Path. It is not clear to me.

NOTE: This converted to local from nfs-driver.

Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>

### CODE REVIEW

**Comment by kunalkushwaha** [comment]
Okay, I got the issue.

``local`` is default driver of docker volume and Should not be used by anyone.

Though still facing issue of kvdb. 

```
Starting volume driver:  newlocal
INFO[0000] Starting REST service on /var/lib/osd/driver/newlocal.sock 
INFO[0000] Starting REST service on /run/docker/plugins/newlocal.sock 
DEBU[0008]                                               Driver=newlocal ID=vol5 Request=create
DEBU[0008]                                               Driver=newlocal ID=vol5 Request=create
WARN[0008] 404 Failed to locate volume: Cannot locate volume vol5  Driver=newlocal ID=vol5 Request=create


```

**Comment by jvinod** [comment]
@kunalkushwaha 
- Note that the nfs driver in the absence of a server defaults to a vfs driver
- regarding the 404 : api/server/docker.go (the volume plugin implementation) expects the vol to exist on a create. The volume should be created separately using 'osd cli' before using it with docker. This will not be necessary after we address https://github.com/libopenstorage/openstorage/issues/7
- you'd still need to implement Mount (bind mount to specified path) and Unmount
- you don't need to implement the pseudo block device inside the vfs path.

**Comment by kunalkushwaha** [comment]
@jvinod Problem is with kvdb driver.
The Path() function of docker.go , tries to get path from kvdb, but it is not getting the ID back.
I think issue is with kvdb code.

Will try to debug in detail.

**Comment by kunalkushwaha** [comment]
@jvinod I got the issue now. Bacially as ID it expects the hex is e.g. ``d9f6d6bd-7cfb-4b89-acf5-26ecd994e213`` instead of name.

Shouldn't be a mapping between ID and name be there, so both can work?

**Comment by kunalkushwaha** [comment]
Fix for https://github.com/libopenstorage/openstorage/issues/9

**Comment by kunalkushwaha** [comment]
all review comments are incorporated.

**Comment by jvinod** [comment]
Everthing else looks good ..

**Comment by jvinod** [comment]
@kunalkushwaha could we add a vfs_test.go? Thanks..

**Pull request merged**
