### PR TITLE
travis: Update Makefile and Travis.yml

### PR DESCRIPTION
**Pull request by lpabon**
Now Travis will test for fmt and vet of files. This WILL make
it fail when this patch is introduced (which is good) because
it will catch many items in the code that need to be fixed.

Signed-off-by: Luis Pabón <luis@portworx.com>

### CODE REVIEW

**Comment by lpabon** [comment]
This failure in Travis means the patch is working 👍

**Comment by adityadani** [comment]
Is it possible to do this per package?
This way we don't keep the build failing and fix every package incrementally.

**Comment by lpabon** [comment]
I think we should fix it all. I have a commit coming with the changes needed to make this work.

**Comment by lpabon** [comment]
This fixes four issues found by vet on the code

**Comment by lpabon** [comment]
Nice! All works and fixed.

**Pull request merged**
