### PR TITLE
Fix make docker-test

### PR DESCRIPTION
**Pull request by peter-edge**
This takes care of varying places where required programs can be, along with flags needed for docker run. In the long term, the exec.Command calls should go away (I have a way to set this up with btrfs I can do in the future so there is no need to mount in the test).

The goal here is a consistent test environment, regardless of installed state.

### CODE REVIEW

**Comment by jvinod** [comment]
Looks good . Since 'which' can find it, would it have been enough to blow away the absolute path and just pass the exec name ?

**Comment by peter-edge** [comment]
Actually I think so, heh.

**Comment by peter-edge** [comment]
I removed the which function, I also removed building btrfs-progs from source and just installing btrfs-tools in the Dockerfile, it passes :)

**Comment by jvinod** [comment]
awesome :)

**Pull request merged**
