### PR TITLE
Add SetTLS function to client so we can support https

### PR DESCRIPTION
**Pull request by pault84**
Hey we need this functionality so we can support https and certificates in our client.

### CODE REVIEW

**Comment by lpabon** [comment]
Could you please provide a unit test function utilizing this new API?

**Comment by lpabon** [comment]
Looks like go fmt issues: https://travis-ci.org/libopenstorage/openstorage/jobs/295951496#L540

**Comment by pault84** [comment]
It changes the client indeed, if we change the actual client code there will be about 10x the amount of code changes required. I can fix the go fmt issues.

**Comment by lpabon** [comment]
@pault84 Ok, Then we probably want some kind of check or test to make sure that once the server is running, this new call returns an error. Or is the expectation that making this call will restart the server at any point?

**Comment by pault84** [comment]
I got your point, i'm going to sit with vinod today and hammer some things out and will do an update on this pr.

**Comment by lpabon** [comment]
Looks good!

**Pull request merged**
